package com.Nxer.TwistSpaceTechnology.common.material;

import static gregtech.api.util.GTLanguageManager.addStringLocalization;

import java.util.Locale;

import cpw.mods.fml.common.FMLCommonHandler;
import goodgenerator.util.CharExchanger;
import gregtech.api.enums.Dyes;
import gregtech.api.enums.Element;
import gregtech.api.enums.MaterialBuilder;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OrePrefixes;
import gregtech.api.enums.SubTag;
import gregtech.api.enums.TCAspects;
import gregtech.api.enums.TextureSet;
import gregtech.api.enums.TierEU;
import gregtech.api.interfaces.IMaterialHandler;
import gregtech.common.render.items.InfinityRenderer;

/**
 * Register new material here by Gregtech Material System
 */
public class MaterialsTST implements IMaterialHandler {

    // spotless:off
    static final int offsetID = 260;
    // ID form 2242 ~ 2298 is available

    private static boolean registered = false;

    public static Materials NeutroniumAlloy;
    public static Materials AxonisAlloy;
    public static Materials Axonium;
    public static Materials Dubnium;

    @Override
    public void onMaterialsInit() {
        NeutroniumAlloy = withMetaItemSubID(
            new MaterialBuilder().setName("NeutroniumAlloy")
                .setDefaultLocalName("Neutronium Alloy")
                .setChemicalFormula("Nt₇Du₂Fl҉?")
                .setIconSet(TextureSet.SET_SHINY)
                .setColor(Dyes._NULL)
                .setARGB(0x00D9DCCB)
                .setTool(98304000, 18, 32.0F)
                .setTurbine(2, 1, 1)
                .addDustItems()
                .addMetalItems()
                .addToolHeadItems()
                .addGearItems()
                .setMeltingPoint(12000)
                .setBlastFurnaceTemp(12500)
                .setBlastFurnaceRequired(true)
                .setAutoGenerateBlastFurnaceRecipes(false)
                .setAutoGeneratedVacuumFreezerRecipe(false)
                .addAspect(TCAspects.ORDO, 1)
                .addAspect(TCAspects.ALIENIS, 2)
                .addAspect(TCAspects.PERDITIO, 3)
                .addAspect(TCAspects.METALLUM, 5)
                .addSubTag(SubTag.METAL)
                .constructMaterial()
                .setProcessingMaterialTierEU(TierEU.RECIPE_UEV),
            offsetID);

        AxonisAlloy = withMetaItemSubID(
            new MaterialBuilder().setName("AxonisAlloy")
                .setDefaultLocalName("Axonis Alloy")
                .setChemicalFormula("۞₅(Hy⚶)₃⸎₂(IcMa)TbSh" + CharExchanger.shifter(9191))
                .setIconSet(TextureSet.SET_SHINY)
                .setColor(Dyes._NULL)
                .setARGB(0x00C54324)
                .setTool(98304000, 18, 96.0F)
                .setTurbine(2, 1, 1)
                .addDustItems()
                .addMetalItems()
                .addToolHeadItems()
                .addGearItems()
                .setMeltingPoint(13000)
                .setBlastFurnaceTemp(13200)
                .setBlastFurnaceRequired(true)
                .setAutoGenerateBlastFurnaceRecipes(false)
                .addAspect(TCAspects.SENSUS, 1)
                .addAspect(TCAspects.PRAECANTATIO, 2)
                .addAspect(TCAspects.METALLUM, 4)
                .addSubTag(SubTag.METAL)
                .constructMaterial()
                .setProcessingMaterialTierEU(TierEU.RECIPE_UIV),
            offsetID + 1);

        Axonium = withMetaItemSubID(
            new MaterialBuilder().setName("Axonium")
                .setDefaultLocalName("Axonium")
                .setChemicalFormula("A☀")
                .setIconSet(TextureSet.SET_SHINY)
                .setColor(Dyes._NULL)
                .setARGB(0x00F32D1B)
                .setTool(1048576000, 24, 480.0F)
                .setTurbine(2, 1, 1)
                .addDustItems()
                .addMetalItems()
                .addPlasma()
                .addToolHeadItems()
                .addGearItems()
                .setMeltingPoint(23000)
                .setBlastFurnaceTemp(26000)
                .setBlastFurnaceRequired(true)
                .setAutoGenerateBlastFurnaceRecipes(false)
                .setAutoGeneratedVacuumFreezerRecipe(false)
                .addAspect(TCAspects.SENSUS, 1)
                .addAspect(TCAspects.PRAECANTATIO, 2)
                .addAspect(TCAspects.VICTUS, 3)
                .addAspect(TCAspects.METALLUM, 5)
                .addSubTag(SubTag.METAL)
                .addOrePrefix(OrePrefixes.nanite)
                .constructMaterial()
                .setProcessingMaterialTierEU(TierEU.RECIPE_UMV),
            offsetID + 2);

        Dubnium = withMetaItemSubID(
            new MaterialBuilder().setName("Dubnium")
                .setDefaultLocalName("Dubnium")
                .setElement(Element.Db)
                .setIconSet(TextureSet.SET_METALLIC)
                .setColor(Dyes._NULL)
                .setARGB(0x00C8C8C8)
                .setTool(0, 2, 1.0F)
                .setTurbine(2, 1, 1)
                .addDustItems()
                .addMetalItems()
                .addPlasma()
                .addToolHeadItems()
                .setMeltingPoint(3231)
                .setBlastFurnaceTemp(3231)
                .setAutoGenerateBlastFurnaceRecipes(false)
                .setAutoGeneratedVacuumFreezerRecipe(false)
                .addAspect(TCAspects.RADIO, 5)
                .addAspect(TCAspects.METALLUM, 3)
                .constructMaterial()
                .setProcessingMaterialTierEU(TierEU.RECIPE_LV),
            offsetID + 3);

        OrePrefixes.nanite.mGeneratedItems.add(Materials.CosmicNeutronium);
        OrePrefixes.nanite.mGeneratedItems.add(MaterialsTST.Axonium);

        initGTMaterialLocalizations();
    }

    private static Materials withMetaItemSubID(Materials material, int metaItemSubID) {
        material.mMetaItemSubID = metaItemSubID;
        return material;
    }

    public static void initClient() {
        Axonium.renderer = new InfinityRenderer();
    }

    public static void init() {
        if (!registered) {
            Materials.add(new MaterialsTST());
            registered = true;
        }
    }

    private static void initGTMaterialLocalizations() {
        if (!isZhCN()) return;

        addGTMaterialLocalization(NeutroniumAlloy, "中子合金");
        addGTMaterialLocalization(AxonisAlloy, "灵韵合金");
        addGTMaterialLocalization(Axonium, "焕律璨金");
        addGTMaterialLocalization(Dubnium, "钅杜");

        addStringLocalization("tst.blockcasings.multi.32767.name", "任意本方块的子方块");
        addStringLocalization("tst.blockmetal01.0.name", "%material块");
        addStringLocalization("tst.blockmetal01.1.name", "%material块");
        addStringLocalization("tst.blockmetal01.2.name", "%material块");
        addStringLocalization("tst.blockmetal01.3.name", "%material块");
        addStringLocalization("tst.blockmetal01.32767.name", "任意本方块的子方块");
    }

    private static void addGTMaterialLocalization(Materials material, String localizedName) {
        addStringLocalization(material.getLocalizedNameKey(), localizedName);
        addStringLocalization("fluid.molten." + material.mName.toLowerCase(Locale.ENGLISH), "熔融" + localizedName);
        addStringLocalization("fluid.plasma." + material.mName.toLowerCase(Locale.ENGLISH), localizedName + "等离子体");
    }

    private static boolean isZhCN() {
        return FMLCommonHandler.instance()
            .getCurrentLanguage()
            .equals("zh_CN");
    }

}
